### ISSUE TITLE
Allow making multacc the default SMS app

### ISSUE THREAD

**Issue by TortoiseWrath** [multacc/multacc#178]
* The only way to read/send SMS in Android 10 because #security
* This will not support RCS in Android 10, but Android 11 is supposed to have an API for that.
* Not for iOS obviously. No iMessage support.

There seems to be no direct way in flutter to make multacc the default SMS app, so we'll have to write custom kotlin code (and use a platform channel) to show the default handler dialog: https://developer.android.com/guide/topics/permissions/default-handlers

**Comment by TortoiseWrath** [comment]
[https://bit.ly/34rL9Fe](multacc/multacc#177) don't mind me, just testing something

**Comment by TortoiseWrath** [comment]
[multacc/multacc#25](https://bit.ly/34rL9Fe)

**Comment by TortoiseWrath** [comment]
[multacc/multacc#177](https://bit.ly/3cb69TD)

**Comment by mayank99** [comment]
@micah-white This is going to need more work. #198 was only the beginning. Right now the app keeps crashing very randomly.

<details>
<summary>Error log</summary>
<pre>
E/AndroidRuntime(10298): FATAL EXCEPTION: main
E/AndroidRuntime(10298): Process: com.multacc, PID: 10298
E/AndroidRuntime(10298): java.lang.RuntimeException: Unable to instantiate receiver com.multacc.SmsReceiver: java.lang.ClassNotFoundException: Didn't find class "com.multacc.SmsReceiver" on path: DexPathList[[zip file "/data/app/com.multacc-QJYBROx6GxuQlsQ2xzMakg==/base.apk"],nativeLibraryDirectories=[/data/app/com.multacc-QJYBROx6GxuQlsQ2xzMakg==/lib/arm, /data/app/com.multacc-QJYBROx6GxuQlsQ2xzMakg==/base.apk!/lib/armeabi-v7a, /system/lib]]
E/AndroidRuntime(10298): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3774)
E/AndroidRuntime(10298): 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
E/AndroidRuntime(10298): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
E/AndroidRuntime(10298): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(10298): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(10298): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(10298): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10298): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(10298): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(10298): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.multacc.SmsReceiver" on path: DexPathList[[zip fil
"/data/app/com.multacc-QJYBROx6GxuQlsQ2xzMakg==/base.apk"],nativeLibraryDirectories=[/data/app/com.multacc-QJYBROx6GxuQlsQ2xzMakg==/lib/arm, /data/app/com.multacc-QJYBROx6GxuQlsQ2xzMakg==/base.apk!/lib/armeabi-v7a, /system/lib]]
E/AndroidRuntime(10298): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(10298): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(10298): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(10298): 	at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
E/AndroidRuntime(10298): 	at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
E/AndroidRuntime(10298): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3767)
E/AndroidRuntime(10298): 	... 8 more
I/Process (10298): Sending signal. PID: 10298 SIG: 9
</pre>
</detail>

**Comment by micah-white** [comment]
Have you written any additional code that might be causing that?

**Comment by mayank99** [comment]
Might need to make the broadcast receiver a subclass of `MainActivity` and we should be good. I will deal with this one day maybe
https://stackoverflow.com/questions/54088421/sending-android-sms-broadcastreceiver-data-to-flutter-through-eventchannel
